#CREATE A DATABASE
CREATE DATABASE SUPERSTORE_SALES;
 
#INGESTED A CLEANED SUPERSTORE_SALES DATA BY USING PYTHON(database_connectivity.py FILE)

#USING THE DATABASE
USE SUPERSTORE_SALES;

#REGIONAL PERFORMANCE:SALES,PROFIT,PROFIT_MARGIN
SELECT 
   REGION,
   ROUND(SUM(SALES),3)AS TOTAL_SALES,
   ROUND(SUM(PROFIT),3) AS TOTAL_PROFIT,
   ROUND(SUM(PROFIT)/SUM(SALES)*100,3) AS PROFIT_MARGIN_PERCENT
   FROM 
       SUPERSTORE
   GROUP BY 
         REGION
   ORDER BY 
		 TOTAL_PROFIT DESC;
      
      
#PRODUCT PROFITABILITY:TOP 10 SUB-CATEGORIES BY PROFIT 
SELECT
    CATEGORY,
    `SUB-CATEGORY`,
    ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT,
    ROUND(SUM(SALES),2) AS TOTAL_SALES
    FROM 
        SUPERSTORE
	GROUP BY
		CATEGORY,`SUB-CATEGORY`
	ORDER BY 
        TOTAL_PROFIT DESC
	LIMIT 10;
    
#OPERATIONAL ANALYSIS:RETURN BY SHIP MODE
SELECT 
    `SHIP MODE`,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(IS_RETURNED) AS TOTAL_RETURNED,
    ROUND((SUM(IS_RETURNED)/COUNT(*))*100,3) AS RETURN_RATE_PERCENT
    FROM 
	    SUPERSTORE
	GROUP BY 
        `SHIP MODE`
	ORDER BY 
		RETURN_RATE_PERCENT DESC;
    
    
#GEOGRAPHICAL REVIEW:BOTTOM 5 STATES BY PROFIT
SELECT
    STATE,
    ROUND(SUM(SALES),3) AS TOTAL_SALES,
    ROUND(SUM(PROFIT),3) AS TOTAL_PROFIT
    FROM
       SUPERSTORE
	GROUP BY 
       STATE 
	ORDER BY 
       TOTAL_PROFIT ASC
	LIMIT 5;
       
       
#SALES AND PROFIT BY SEGMENT
SELECT
    Segment,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT) / SUM(SALES)) * 100, 2) AS PROFIT_MARGIN_PERCENT
FROM
    SUPERSTORE
GROUP BY
    SEGMENT
ORDER BY
    TOTAL_PROFIT DESC;
    



